language: python
python:
    - 3.6

notifications:
    email: false

env:
  - ANSIBLE_VERSION=devel
  - ANSIBLE_VERSION=stable-2.7
  - ANSIBLE_VERSION=stable-2.5

before_install:
  - pip install tox
  - git clone --recursive --depth=1 -b $ANSIBLE_VERSION https://github.com/ansible/ansible
  - pip install ./ansible

script:
    - tox
